version: '3'
services:
    db:
        image: percona:5.7
        volumes:
            - db_data:/var/lib/mysql
            - ./import:/docker-entrypoint-initdb.d:ro
        environment:
            MYSQL_ROOT_PASSWORD: not-so-secure
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: not-so-secure

    memcached:
        image: memcached:1.5

    php:
        depends_on:
            - db
            - memcached
        build: .
        ports:
            - "8080:8080"
        volumes:
            - ./:/app
            - ./plugin:/app/public/content/plugins/cool-plugin
        environment: 
            - DOCUMENT_ROOT=/app/public
            - WP_CONTENT_DIR=/app/public/wp
            - STACK_MEDIA_PATH=/app/public/content/uploads
            - WP_HOME=http://localhost:8080
            - WP_SITEURL=http://localhost:8080/wp
            - WP_ENV=development
            - PHP_REQUEST_TIMEOUT=300

volumes:
    db_data: {}